### ISSUE TITLE
My notes just disappeared!

### ISSUE THREAD

**Issue by jtrees** [lainsce/notejot#117]
I just restarted my PC and saw that my notes have disappeared! What happened? Is there any way to get them back?

I am using version 1.5.5.

**Comment by lainsce** [comment]
I've tweeted about this, it was a backend change:
https://twitter.com/lainsdev/status/1097835585417420801?s=09

**Comment by jtrees** [comment]
I see. The change is a good move. And thanks for the link, I can now restore my notes.

I'm curious why you didn't implement an automatic migration. Doesn't this change affect every single user and every single note without exception?

**Comment by lainsce** [comment]
Because if I do that, the next release I'd have to remove the code, and so on. At least now there's not gonna be any new backend changes anymore.

**Comment by qneville** [comment]
Hey @lainsce sorry to dig up dead stuff here, but I just lost all my notes after an update and it looks like your Twitter account (and the original Tweet) is gone. Is there still a method of recovery? Thanks!

**Comment by saligari** [comment]
I'm sorry but there isn't any mention anywhere as far as I can see that one should always back up his notes because the app may eat it at any update. Honestly, updates that result in the notes disappearing shouldn't go through.

Nice app and all but it's no more than a toy if it can't be trusted to not randomly delete my notes when really the only thing this app should do is hold my notes. I only used this app for a few days and I'm never touching it again now that it screwed me.

**Comment by lainsce** [comment]
I wrote where the notes are cached both on this repo, and the description in Software. It shouldn't be missable, but I'm sorry if it wasn't clear or obvious enough. The next update will feature a new backend that will **surely 100% not eat** your notes. Plus I am not a company, I am only one developer.
