### ISSUE TITLE
[Request]: Move the three buttons from the bottom to the top in the note. (+notejot in the system tray).

### ISSUE THREAD

**Issue by tnilzon** [lainsce/notejot#148]
Hi, I have a request. Would you consider moving the three buttons in the note to the top instead? That would then make it possible to resize a note to a smaller size with the buttons still visible (if you are making a small note with just a few words).

Also, a second request: I think it would be a good option to be able to have `notejot` to be in the system tray (and with some options through a right click menu, maybe). Then it could be added to autostart, and always be easy to reach in the tray. Thanks!

My system:
>Kernel: 5.5.13-1-MANJARO x86_64 bits: 64 
Desktop: KDE Plasma 5.18.3 Distro: Manjaro Linux

![notjot2](https://user-images.githubusercontent.com/6920015/78557458-1f1d1c00-7811-11ea-9b20-ea5b113c07bb.png)

**Comment by lainsce** [comment]
Sorry, but both are anti-patterns in the user interface, that don't go well with the design of the application, especially the system tray; elementary OS doesn't have one so there's no way I'd add one just for corner cases. As for the buttons in the headerbar instead of the bottom, that would reduce the space to title your note in a horrible way.
