### ISSUE TITLE
Notes vanished after starting multiple notes at once

### ISSUE THREAD

**Issue by qumberrizvi** [lainsce/notejot#154]
I had one note since days and everything was good.
Today, I needed to add a couple more.
As soon as I created new notes, all three of them got emptied. Only the titles of each note are still intact.
![screenshot](https://user-images.githubusercontent.com/12488086/83746730-2cbe1900-a67d-11ea-9582-adf484ab04f3.png)

There are two files files in the storage folder `saved_notes.json` and `saved_notes.json~`. Both files contain the following json:
![saved_notes.json](https://user-images.githubusercontent.com/12488086/83747262-fe8d0900-a67d-11ea-8c50-dba679bb4850.png)
![saved_notes.json~](https://user-images.githubusercontent.com/12488086/83747150-d6050f00-a67d-11ea-933b-05571a6a87f1.png)

Did I do something wrong or did I discover a weird bug?

**Edit**: I believe I closed the notes using Super+Q hotkey before it happened, if that helps.

**Comment by lainsce** [comment]
Notejot is being rewritten from the ground up and will be released as soon as Hera+1 (The next OS release) is up due to using newer technologies. Hang tight, but if you're adventurous, feel free to test it out by going on the existing single Pull Request before it is even merged into the main branch. Just have to hunt down the new libraries yourself.
It'll also fix this bug.

**Comment by qumberrizvi** [comment]
Thank you, I'll give the PR a try. And thanks for great work. ❤️
