### ISSUE TITLE
Note is deleted when new note is created and edited

### ISSUE THREAD

**Issue by luigimassa** [lainsce/notejot#155]
Hello, 
### bug
I found this bug:
 - open a note
 - insert more text with multple paragraph
 - close the note with X icon
 - reopen  the note
 - the note is ok
Now...
 - open previous note
 - create new note
 - insert new text with multiple paragraph, eg 3 paragraph
 - close the prevoius note with X 
 - insert other text, eg 3 paragraph
 - close also this note with icon "X"
 - reopen all notes

In the first note the text disappear

### version 
branch master
my operating system is Ubuntu 20.04
I've installed notejot with flatpak and the compiled and installed notejote from source because the version of notejot in flatpak is not updated.

### video
[video bug](https://drive.google.com/file/d/1PHFBYZISgUuJCZKeZ6lrV9YAaWadtSaK/view)

Thanks in advance!

**Comment by lainsce** [comment]
Notejot is being rewritten from the ground up and will be released as soon as Hera+1 (The next OS release) is up due to using newer technologies. Hang tight, but if you're adventurous, feel free to test it out by going on the existing single Pull Request before it is even merged into the main branch. Just have to hunt down the new libraries yourself.
It'll also fix this bug.

**Comment by luigimassa** [comment]
Thanks
How can I test  new 2.0?

**Comment by lainsce** [comment]
You're going to have to wait until the next release of elementary OS since I'm using newer libraries that aren't found in Hera.

**Comment by luigimassa** [comment]
ok,
I waiting
thanks
