### ISSUE TITLE
Formatting buttons do not remove formatting

### ISSUE THREAD

**Issue by fastrizwaan** [lainsce/notejot#211]
From windows, we all use Formatting buttons to apply and remove formatting on selected text or apply formatting to text before typing it. Current behavior of not removing formatting by the same format button is totally out of standard formatting behavior by Rich Text Editors.

![formatting buttons don't remove formatting](https://user-images.githubusercontent.com/1161682/109024595-ef565b80-76e3-11eb-845f-16b569006271.gif)

**Comment by lainsce** [comment]
Each button applies a JavaScript code to the note's HTML, and so, the remove all formatting button is the command in JavaScript to return code to plaintext without formatting. It's not possible to do a toggle if bold, because how does the code know that this or that is bold, for ex? Yep, that's why the remove formatting button exists.
