### ISSUE TITLE
[Feature Request] Context menu for notes in list view

### ISSUE THREAD

**Issue by janopae** [lainsce/notejot#359]
It would be nice if the three-dot-menu above the note editor could be a context menu in the list view instead.

The reason is: These options are not related to the edit view, but rather to the note as a whole. Especially on mobile devices, it shouldn't be necessary to leave the list view in order to delete/recolour/pin a note. Especially the "pin" feature has a direct influence on the list view and not on the edit view.

**Comment by lainsce** [comment]
That menu was also originally on each note as a context menu, but due to mobile, I had removed it in favour of only the three-dot menu. I could redesign this so that the three dot menu is on each note item in the list view instead.

**Comment by lainsce** [comment]
I tried to modify this so that the context menu was in every note in the listview, but due to how the backend operates, I couldn't. I believe that opening a note to pin it/delete it makes sense than just going in and deleting/pinning one without consideration, because at least you open what you are deleting or pinning first.
