### ISSUE TITLE
Features Needed

### ISSUE THREAD

**Issue by passionate2023** [lainsce/notejot#406]
- Import menu to import txt files, docx files
- Option to share the whole note for other users to view/search what we see in web application. basically the shared users should be able to view, search but should not have the privilege to edit/delete the notes of the entire notebook
- type ahead with number of matches on typing and highlight text in search results in 1st level and second level navigation
- navigation arrows to navigate the occurrences of the searched keyword in the notes when clicked via search result

**Comment by lainsce** [comment]
> * Import menu to import txt files, docx files

Notejot isn't this kind of app.

> * Option to share the whole note for other users to view/search what we see in web application. basically the shared users should be able to view, search but should not have the privilege to edit/delete the notes of the entire notebook

There's a Export Note function in the note's menu

> * type ahead with number of matches on typing and highlight text in search results in 1st level and second level navigation

This is already a thing, just no # of matches displayed. Highlight isn't necessary because filtering already shows which notes have the term.

> * navigation arrows to navigate the occurrences of the searched keyword in the notes when clicked via search result

This isn't needed because the relevant notes are displayed with a scrollbar, thus one can get to the desired note between the notes found easily.
