### ISSUE TITLE
Re-sizable window

### ISSUE THREAD

**Issue by basjam** [lainsce/notejot#51]
Feature request:  (Enhancement??)

Thank you for this awesome app. It would be helpful if I could re-size the window to suite my notes.

**Comment by lainsce** [comment]
It is by design that the windows are this size. If you want more space, you just need to add a new note via the menu.

**Comment by hfel** [comment]
Would like to see this feature too. The problem isn't a lack of space; rather, some notes are so short that having note windows of mostly empty space is not very elegant.

**Comment by eljefuri** [comment]
I strongly think you should reconsider this @lainsce 

Notejot is right on the verge of being a very useful application for me, very much as its counterpart was for generations on Mac OS and Mac OS X systems. But the lack of resizeability actually renders it useless for the kinds of things that I at least used it for in the past.

**Comment by lainsce** [comment]
How about this:
An option below note colors, that sets the size of the sticky note?

**Comment by eljefuri** [comment]
How about just using standard window behavior e.g. resize-at-edges with the mouse?

**Comment by lainsce** [comment]
There's no technical reason, it just goes against what I envisioned for the User Experience of the application. Sticky Notes don't resize in the real world, why should these virtual ones do?

**Comment by eljefuri** [comment]
Because sticky notes on a computer are a metaphor and not exclusively used for the same things as paper sticky notes.

**Comment by lainsce** [comment]
Yes, but _my vision_, _my idea_ of Notejot is to have one note for each type of thing you might wanna write.
Not a big-ass note with everything on it. Think about it like Keep Notes on Android. You don't have one note there for everything, because why have a "Add new note button" there too?

**Comment by eljefuri** [comment]
Certainly you are free to write this application to your precise vision only for yourself, never deviating from that path under any circumstance. But is that what you really want? Besides, what exactly stops you from continuing to use the app the way you want to use it, even if the window is able to be resized for the benefit of others?

I cannot comment on Keep Notes because I have never used it.

**Comment by lainsce** [comment]
Think about it like this:
Let's imagine there's a root window governing all the windows of Notejot. That root window glues each as if the windows were only widgets. That's how Notejot is. Each Window is just a widget of a big imaginary window.

**Comment by eljefuri** [comment]
By the way, I never said anything about _"one big-ass note with everything on it"_. Stickies usage at least varied significantly.

From the clean, but active:

![20180313-sticky-01](https://user-images.githubusercontent.com/44387419/48303493-4e0c6100-e53d-11e8-8de2-def062730ca2.jpg)

To the daily driver:

![7ubdk](https://user-images.githubusercontent.com/44387419/48303492-4d73ca80-e53d-11e8-918c-68fcfaf6fb7c.jpg)

To the insane:

![screen shot 2013-06-30 at 8 08 23 am](https://user-images.githubusercontent.com/44387419/48303494-4ea4f780-e53d-11e8-9826-fa522490859f.png)

**Comment by eljefuri** [comment]
@lainsce I see. Well, I originally asked about technical limitations before waxing poetic re: usability. If it is a gross technical challenge, then that is an entirely other manner.

**Comment by hfel** [comment]
I concur with @eljefuri here: it is of course up to you as a developer working on this for free to design the app the way you see fit and you don't really have any obligations towards the users other than those you decide on yourself, but different people prefer different ways of doing things (which is what a lot of Linux is about), so if you are interested in providing a good experience to the userbase in its variety, you could include this feature as well. 

For me personally, it's about aesthetics and usability: different notes have different lengths and structures, and having the same size for each looks clunky and makes navigation harder. And yeah, the reason we use digital tools in the first place is because they improve upon the functionality of analog ones, so to wax philosophical a bit, digital sticky notes _should_ evolve depending on their context and inherent possibilities, because they are _not_ the same as analog ones anymore. But again, there's no reason for you or anyone else who prefers a simple transplant of the analog experience into the digital world to not be able to have that, it's just that others have different expectations, so why not make both options available? ;)

**Comment by aljelly** [comment]
> I concur with @eljefuri here: it is of course up to you as a developer working on this for free to design the app the way you see fit and you don't really have any obligations towards the users other than those you decide on yourself, but different people prefer different ways of doing things (which is what a lot of Linux is about), so if you are interested in providing a good experience to the userbase in its variety, you could include this feature as well.
> 
> For me personally, it's about aesthetics and usability: different notes have different lengths and structures, and having the same size for each looks clunky and makes navigation harder. And yeah, the reason we use digital tools in the first place is because they improve upon the functionality of analog ones, so to wax philosophical a bit, digital sticky notes _should_ evolve depending on their context and inherent possibilities, because they are _not_ the same as analog ones anymore. But again, there's no reason for you or anyone else who prefers a simple transplant of the analog experience into the digital world to not be able to have that, it's just that others have different expectations, so why not make both options available? ;)

I agree. Actually, a while ago I thought about this and I had the same analogy in mind. It also seems very weird that, while nearly every other window in elementary OS is resizable, Notejot's windows aren't. The lack of resizing behaviour ends up being inconsistent with mostly every other elementary OS window. It could actually be surprising for users who are expecting to be able to resize the window as normal like with every other window they've encountered before. _"Huh? Why can't I resize it?"_

(... actually, I found myself thinking that very thing when I first used Notejot. Honestly, I found it annoying!)

I definitely concur about it affecting usability as well. Notejot's designed for writing short amounts of text, but even then it's still useful and makes sense to be able to resize it when you have too much text in the window. This is something digital sticky notes can do that you can't do with real sticky notes in the real world, in other words it'd be an improvement over the real thing. If people could resize the paper they were writing on when they wrote way too near the edge they probably would.

I do think it would be an improvement to Notejot to add resizing, and considering the above points I made, I don't see any design reason why it wouldn't be a good idea. This is a very simple and intuitive thing. It's kind of like asking, _"Calendars don't resize in the real world, so why can I resize elementary's Calendar"?_ Well, because it's a very simple improvement (both development and design wise) over the real thing, every other window does it, and it's useful! Maybe I need to see the full text of my events!

Indeed, you don't have any obligation to add this. But in the name of good design, I urge you to reconsider.

**Comment by eljefuri** [comment]
@lainsce [Thank you!](https://github.com/lainsce/notejot/commit/770b83242eab543ed5185c39fbf9e32191449d29)
